### ISSUE TITLE
Add min, max input fields to set image intensity range

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue-ui#23]

**Comment by soichih** [comment]
I can/should probably contribute to this item, but with min/max/thresholding, I think it will be already on-par with ACElab brainviewer that we are currently using (and no longer maintained?) 

Here are the controls that are available through brainviewer

![image](https://user-images.githubusercontent.com/923896/140810548-b3684880-b80c-4bf2-98c7-e4684ac61ec3.png)

Once this is done, I can add it to the available visualizer for various 3D nifti datatypes on brainlife.io

**Comment by hanayik** [comment]
@soichih , thanks! I think this could be a great first contribution. Hold off for a week or two so that I can update some observables (events) and how they are used within the NiiVue-UI project. #19. It will be much cleaner.

**Comment by soichih** [comment]
OK no rush! 

By the way, another visualizer that I'd like to add to brainlife is https://github.com/OHIF/Viewers I think this is mainly for dicom, but I believe flywheel uses it to somehow display nifti. I am not sure how complex you want niivue-ui to be, but it might be good to draw some road map on features that we'd like to add near/long term?
